version: '{build}'
image:
  - Visual Studio 2015
environment:
  appveyor_repo_tag: true
  BINTRAY_APIKEY:
    secure: HYhL/Jc4o1S5+tXN9c0NFFcwXpllXB5ykH0gA2hn4tc7CWLN3LHZszPFwHoO2onc
clone_folder: '%SYSTEMDRIVE%\gopath\src\github.com\mbtproject\mbt'
before_build:
  - cmd: mkdir %SYSTEMDRIVE%\downloads
  - cmd: mkdir %SYSTEMDRIVE%\go386
  - cmd: curl -L -o %SYSTEMDRIVE%\downloads\pkg-config_0.26-1_win32.zip http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/pkg-config_0.26-1_win32.zip
  - cmd: curl -L -o %SYSTEMDRIVE%\downloads\glib_2.28.8-1_win32.zip http://ftp.gnome.org/pub/gnome/binaries/win32/glib/2.28/glib_2.28.8-1_win32.zip
  - cmd: curl -L -o %SYSTEMDRIVE%\downloads\gettext-runtime_0.18.1.1-2_win32.zip http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/gettext-runtime_0.18.1.1-2_win32.zip
  - cmd: curl -L -o %SYSTEMDRIVE%\downloads\go.zip https://storage.googleapis.com/golang/go1.9.windows-386.zip
  - ps: Expand-Archive $ENV:SYSTEMDRIVE\downloads\pkg-config_0.26-1_win32.zip -DestinationPath $ENV:SYSTEMDRIVE/ -Force
  - ps: Expand-Archive $ENV:SYSTEMDRIVE\downloads\glib_2.28.8-1_win32.zip -DestinationPath $ENV:SYSTEMDRIVE/ -Force 
  - ps: Expand-Archive $ENV:SYSTEMDRIVE\downloads\gettext-runtime_0.18.1.1-2_win32.zip -DestinationPath $ENV:SYSTEMDRIVE/ -Force  
  - ps: Expand-Archive $ENV:SYSTEMDRIVE\downloads\go.zip -DestinationPath $ENV:SYSTEMDRIVE/go386/ -Force  
  - cmd: SET GOROOT=%SYSTEMDRIVE%\go386\go
  - cmd: SET GOPATH=%SYSTEMDRIVE%\gopath
  - cmd: SET PATH=%SYSTEMDRIVE%\bin;%SYSTEMDRIVE%\MinGW\bin;%SYSTEMDRIVE%\go386\go\bin;%PATH%
build_script: 
  - cmd: ./scripts/build_win.bat
  - ps: ./scripts/appveyor_publish.ps1
artifacts:
  - path: build
    name: mbt
    type: zip
